const DEFAULT_MOMENT_FORMAT = 'HH:mm:ss DD.MM.YYYY';
const DEFAULT_MOMENT_FORMAT_DATE_ONLY = 'DD.MM.YYYY';
const DEFAULT_MOMENT_FORMAT_TIME_ONLY = 'HH:mm:ss';
const DEFAULT_PICKER_FORMAT = 'hh:mm dd.MM.yyyy';
const DEFAULT_PICKER_FORMAT_DATE_ONLY = 'dd.MM.yyyy';

export {
  DEFAULT_MOMENT_FORMAT,
  DEFAULT_MOMENT_FORMAT_DATE_ONLY,
  DEFAULT_MOMENT_FORMAT_TIME_ONLY,
  DEFAULT_PICKER_FORMAT,
  DEFAULT_PICKER_FORMAT_DATE_ONLY,
};
